### PR TITLE
IDA 7.5 Python 3.8.7 compatibility

### PR DESCRIPTION
**Pull request by cichyx96**
IDA 7.5 Python 3.8.7 compatibility

### CODE REVIEW

**Review by PollyP — COMMENTED** [review]
Hi, thanks for updating this. I'm a little confused by line 7 in the README.md. Is there something missing in that comment?

**Comment by mzc96** [comment]
I tested it with NumPy installed just by typing `pip install numpy`, so I wasn't sure if it will work on the version that you specified.
You can try to run it on your setup, If it works then leave your version :).

**Comment by cichyx96** [comment]
python=>numpy. Just edited it. Feel free to edit it to your version if you want :).

**Comment by PollyP** [comment]
I am going to bump the plugin version number, but otherwise looks great. I'm going to merge this now. Again, thanks for the PR!

**Pull request merged**
